// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/redux/store-provider";
import { ThemeProvider } from "@/components/theme-provider";
import ClientLayout from "@/components/custom/custom-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <StoreProvider>
          <body className={inter.className}>
            <ClientLayout>{children}</ClientLayout>
          </body>
        </StoreProvider>
      </ThemeProvider>
    </html>
  );
}
